# Generated by Django 3.1.6 on 2021-02-11 16:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="название статьи"),
                ),
                ("content", models.TextField(verbose_name="текст статьи")),
                (
                    "pub_date",
                    models.DateTimeField(auto_now=True, verbose_name="дата публикации"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="articles/", verbose_name="Изображение"
                    ),
                ),
                ("url", models.SlugField(max_length=160, unique=True)),
                ("draft", models.BooleanField(default=False, verbose_name="черновик")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
