# Generated by Django 3.1.6 on 2021-02-11 17:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=100, verbose_name="название статьи"),
        ),
    ]
