# Generated by Django 3.1.6 on 2021-02-11 17:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_auto_20210211_2031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200, verbose_name="название статьи"),
        ),
    ]
