# Generated by Django 3.1.6 on 2021-02-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_auto_20210211_2033"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="image",
            new_name="art_image",
        ),
    ]
