# Generated by Django 3.1.6 on 2021-02-16 11:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_remove_article_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="url",
            field=models.SlugField(max_length=130, null=True),
        ),
    ]
